import logo from "./assets/images/Classic AB mug.png";

const products = [
  {
    id: 1,
    name: "Classic Ab mug",
    price: "7,499.00",
    rating: "4.2",
    image,
  },
  {
    id: 2,
    name: "Red heart white mug",
    price: "6,500.00",
    rating: "4.1",
    image,
  },
  {
    id: 3,
    name: "Cool brown mug",
    price: "5,500.00",
    rating: "4.5",
    image,
  },
  {
    id: 4,
    name: "Peach mug",
    price: "7,500.00",
    rating: "4.9",
    image,
  },
  {
    id: 5,
    name: "Happy yellow mug",
    price: "7,000.00",
    rating: "4.5",
    image,
  },
  {
    id: 6,
    name: "Yellow & orange mug",
    price: "8,000.00",
    rating: "4.8",
    image,
  },
  {
    id: 7,
    name: "Blue Monday mug",
    price: "9,000.00",
    rating: "4.0",
    image,
  },
  {
    id: 8,
    name: "Smiley face mug",
    price: "8,000.00",
    rating: "4.4",
    image,
  },
  {
    id: 9,
    name: "Plain white mug",
    price: "4,000.00",
    rating: "4.5",
    image,
  },
  {
    id: 10,
    name: "“Best boss ever” mug",
    price: "6,000.00",
    rating: "4.1",
    image,
  },
  // CHANGE THE ID NUMBERS =======
  {
    id: 1,
    name: "White metal mug",
    price: "5,500.00",
    rating: "4.1",
    image,
  },
  {
    id: 1,
    name: "Winky face mug",
    price: "6,500.00",
    rating: "4.2",
    image,
  },
  {
    id: 1,
    name: "Breakfast mug",
    price: "4,500.00",
    rating: "3.8",
    image,
  },
  {
    id: 1,
    name: "Black wide mug",
    price: "4,000.00",
    rating: "3.9",
    image,
  },
  {
    id: 1,
    name: "World’s best boss",
    price: "5,000.00",
    rating: "4.0",
    image,
  },
  {
    id: 1,
    name: "Slim yellow mug",
    price: "6,000.00",
    rating: "3.6",
    image,
  },
  {
    id: 1,
    name: "The Boss mug",
    price: "3,000.00",
    rating: "3.6",
    image,
  },
  {
    id: 1,
    name: "Blue coffee mug",
    price: "6,800.00",
    rating: "3.7",
    image,
  },
  {
    id: 1,
    name: "White wide lip mug",
    price: "6,200.00",
    rating: "3.8",
    image,
  },
  {
    id: 1,
    name: "White wide mug",
    price: "6,400.00",
    rating: "4.8",
    image,
  },
];

export default products;
